FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build-env
WORKDIR /app

# Copy csproj
COPY . .

# restore as distinct layers
RUN dotnet restore Nozomi.WSS/Nozomi.WSS.csproj

# Copy everything else and build
COPY . ./
RUN dotnet publish Nozomi.WSS/Nozomi.WSS.csproj -c Release -o out

# Build runtime image
FROM mcr.microsoft.com/dotnet/core/aspnet:2.2
WORKDIR /app
COPY --from=build-env /app/Nozomi.WSS/out .
RUN ls
ENTRYPOINT ["dotnet", "Nozomi.WSS.dll"]
